# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded sc_ca_sttp_client 1.0 [list source [file join $dir sc-ca/client_glue.tcl]]
package ifneeded sc_ca_sttp_server 1.0 [list source [file join $dir sc-ca/server_glue.tcl]]
package ifneeded sttp 1.0 [list source [file join $dir sttp.tcl]]
package ifneeded sttp_client 1.0 [list source [file join $dir client/client.tcl]]
package ifneeded sttp_client_pgtcl 1.0 [list source [file join $dir client/pgtcl.tcl]]
package ifneeded sttp_debug 1.0 [list source [file join $dir debug.tcl]]
package ifneeded sttp_display 1.0 [list source [file join $dir display/display.tcl]]
package ifneeded sttp_display_test 1.0 [list source [file join $dir display/test.tcl]]
package ifneeded sttp_locks 1.0 [list source [file join $dir server/lock.tcl]]
package ifneeded sttp_optimizer 1.0 [list source [file join $dir client/optimizer.tcl]]
package ifneeded sttp_pgtcl 1.0 [list source [file join $dir pgsql.tcl]]
package ifneeded sttp_server 1.0 [list source [file join $dir server/server.tcl]]
package ifneeded sttpx 1.0 [list source [file join $dir display/util.tcl]]
