name: Mac tcl8 build-install

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        set -x
        brew update
        brew reinstall tcl-tk@8
        brew install boost
    - name: configure
      run: |       
        autoreconf -vi
        PREFIX=/opt/homebrew/opt/tcl-tk@8
        ./configure --with-tcl=$PREFIX/lib --prefix=$PREFIX
    - name: make
      run: make
    - name: install
      run: sudo make install
